"""empty message

Revision ID: 230bcbc662f3
Revises: 542345d1af6e
Create Date: 2021-06-01 15:06:50.851010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230bcbc662f3'
down_revision = '542345d1af6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('specifications',
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.PrimaryKeyConstraint('equipment_id', 'server_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specifications')
    op.drop_table('equipment')
    # ### end Alembic commands ###
