"""empty message

Revision ID: 9da63c5db648
Revises: d675ade5afd1
Create Date: 2021-06-05 10:57:19.251778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da63c5db648'
down_revision = 'd675ade5afd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('token', sa.String(length=16), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'token')
    # ### end Alembic commands ###
